from __future__ import annotations

import frappe
from frappe.sessions import get_csrf_token

from central.api.auth import build_auth_context

no_cache = 1


def get_context(context):
	"""Boot data for Central's public auth pages and signed-in dashboard.

	The page is generated by the TypeScript frappe-ui build (`yarn build`
	copies the hashed `index.html` to this `www/dashboard.html`). The build's
	jinjaBootData plugin injects a loop that sets `window[key] = boot[key]` for
	each key below, so the SPA can read `window.csrf_token`, `window.user`, etc.
	at load time. frappe-ui's request layer sends `window.csrf_token` as the
	X-Frappe-CSRF-Token header, so its POST (write) API calls aren't rejected.
	"""
	context.no_cache = 1
	# init_context() already set context.boot via get_website_settings()
	# (lang, sysdefaults, assets_json, etc.). Extend it rather than replace so
	# those framework defaults survive alongside the SPA's auth essentials.
	boot = context.boot or frappe._dict()
	boot["csrf_token"] = get_csrf_token()
	boot["user_type"] = getattr(frappe.session.data, "user_type", None)
	boot.update(build_auth_context())
	# Development benches expose Socket.IO directly; production proxies it.
	if frappe.conf.developer_mode:
		boot["socketio_port"] = frappe.conf.socketio_port
	boot["site_name"] = frappe.local.site
	context.boot = boot
	return context
