/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddMethodDialog: typeof import('./src/components/AddMethodDialog.vue')['default']
    AuthShell: typeof import('./src/components/auth/AuthShell.vue')['default']
    BillingCard: typeof import('./src/components/billing/BillingCard.vue')['default']
    BillingContactTaxCard: typeof import('./src/components/billing/BillingContactTaxCard.vue')['default']
    CapabilityList: typeof import('./src/components/team/CapabilityList.vue')['default']
    CollectionActionBanner: typeof import('./src/components/billing/CollectionActionBanner.vue')['default']
    ConfigDesigner: typeof import('./src/components/servers/ConfigDesigner.vue')['default']
    CreateTeamDialog: typeof import('./src/components/team/CreateTeamDialog.vue')['default']
    EditBillingProfileDialog: typeof import('./src/components/billing/EditBillingProfileDialog.vue')['default']
    EmptyState: typeof import('./src/components/common/EmptyState.vue')['default']
    ErrorBoundary: typeof import('./src/components/common/ErrorBoundary.vue')['default']
    EstimatedCard: typeof import('./src/components/billing/EstimatedCard.vue')['default']
    InvitationRowActions: typeof import('./src/components/team/InvitationRowActions.vue')['default']
    InviteMemberDialog: typeof import('./src/components/team/InviteMemberDialog.vue')['default']
    InvoiceListView: typeof import('./src/components/billing/InvoiceListView.vue')['default']
    LadderSelect: typeof import('./src/components/servers/LadderSelect.vue')['default']
    ListView: typeof import('./src/components/common/list-view/ListView.vue')['default']
    ListViewPagination: typeof import('./src/components/common/list-view/ListViewPagination.vue')['default']
    ListViewState: typeof import('./src/components/common/list-view/ListViewState.vue')['default']
    MapMessageCard: typeof import('./src/components/servers/MapMessageCard.vue')['default']
    MembersPanel: typeof import('./src/components/team/MembersPanel.vue')['default']
    MeteredServicesCard: typeof import('./src/components/billing/MeteredServicesCard.vue')['default']
    NotificationBell: typeof import('./src/components/notifications/NotificationBell.vue')['default']
    NotificationItem: typeof import('./src/components/notifications/NotificationItem.vue')['default']
    NotificationPreferences: typeof import('./src/components/notifications/NotificationPreferences.vue')['default']
    OtpInput: typeof import('./src/components/common/OtpInput.vue')['default']
    PageHeader: typeof import('./src/components/common/PageHeader.vue')['default']
    PauseBillingDialog: typeof import('./src/components/billing/PauseBillingDialog.vue')['default']
    PaymentMethodRowActions: typeof import('./src/components/billing/PaymentMethodRowActions.vue')['default']
    PaymentMethodsCard: typeof import('./src/components/billing/PaymentMethodsCard.vue')['default']
    PlanCards: typeof import('./src/components/servers/PlanCards.vue')['default']
    PlanGroup: typeof import('./src/components/servers/PlanGroup.vue')['default']
    ProviderAvatar: typeof import('./src/components/servers/ProviderAvatar.vue')['default']
    ReceivedInvitationsPanel: typeof import('./src/components/team/ReceivedInvitationsPanel.vue')['default']
    RemovePaymentMethodDialog: typeof import('./src/components/billing/RemovePaymentMethodDialog.vue')['default']
    ResizeServerDialog: typeof import('./src/components/servers/ResizeServerDialog.vue')['default']
    RightSidebar: typeof import('./src/components/common/RightSidebar.vue')['default']
    RoleBuilderDialog: typeof import('./src/components/team/RoleBuilderDialog.vue')['default']
    RoleMatrix: typeof import('./src/components/team/RoleMatrix.vue')['default']
    RoleRowActions: typeof import('./src/components/team/RoleRowActions.vue')['default']
    RolesPanel: typeof import('./src/components/team/RolesPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SentInvitationsPanel: typeof import('./src/components/team/SentInvitationsPanel.vue')['default']
    ServerMap: typeof import('./src/components/servers/ServerMap.vue')['default']
    ServerOnboarding: typeof import('./src/components/servers/ServerOnboarding.vue')['default']
    ServerRowActions: typeof import('./src/components/servers/ServerRowActions.vue')['default']
    SocialLoginButtons: typeof import('./src/components/auth/SocialLoginButtons.vue')['default']
    SplitView: typeof import('./src/components/common/SplitView.vue')['default']
    StopBillingCard: typeof import('./src/components/billing/StopBillingCard.vue')['default']
    SubscribeServiceDialog: typeof import('./src/components/billing/SubscribeServiceDialog.vue')['default']
    SubscriptionRowActions: typeof import('./src/components/billing/SubscriptionRowActions.vue')['default']
    SubscriptionsCard: typeof import('./src/components/billing/SubscriptionsCard.vue')['default']
    TeamMemberRowActions: typeof import('./src/components/team/TeamMemberRowActions.vue')['default']
    TerminateDialog: typeof import('./src/components/servers/TerminateDialog.vue')['default']
    TopupDialog: typeof import('./src/components/TopupDialog.vue')['default']
    ValidatedFormControl: typeof import('./src/components/common/formComponents/ValidatedFormControl.vue')['default']
    WalletCard: typeof import('./src/components/billing/WalletCard.vue')['default']
    WalletHistoryPanel: typeof import('./src/components/billing/WalletHistoryPanel.vue')['default']
    WorldDots: typeof import('./src/components/servers/WorldDots.vue')['default']
  }
}
